version: '3.8'

services:
  symfony_app:
    build:
      context: ./project/
      dockerfile: docker/php/Docker
    volumes:
      - ./project:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - symfony_db
      - rabbitmq
      - redis
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@symfony_db:3306/${MYSQL_DATABASE}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}
      REDIS_HOST: ${REDIS_HOST}
      WORKER_COUNT: ${WORKER_COUNT}
      QUEUE_LENGTH_THRESHOLD_HIGH: ${QUEUE_LENGTH_THRESHOLD_HIGH}
      QUEUE_LENGTH_THRESHOLD_LOW: ${QUEUE_LENGTH_THRESHOLD_LOW}
      MIN_WORKERS: ${MIN_WORKERS}
      MAX_WORKERS: ${MAX_WORKERS}

  symfony_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    image: nginx:latest
    container_name: symfony_webserver
    ports:
      - "8000:80"
    volumes:
      - ./project:/var/www/html
      - ./project/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony_app

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./project/
      dockerfile: docker/php/Docker
    depends_on:
      - rabbitmq
      - symfony_db
      - redis
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@symfony_db:3306/${MYSQL_DATABASE}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      REDIS_HOST: ${REDIS_HOST}
    command: php bin/console messenger:consume async
    volumes:
      - ./project:/var/www/html
    restart: on-failure

volumes:
  db_data:
  rabbitmq_data: