version: '3.8'

services:
  app:
    container_name: symfony_app
    build:
      context: ./project/
      dockerfile: docker/php/Docker
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    image: nginx:latest
    container_name: symfony_webserver
    ports:
      - "8000:80"
    volumes:
      - ./project:/var/www/html
      - ./project/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: