framework:
    cache:
        # Optional: используйте уникальный префикс для кэш-ключей
        # prefix_seed: your_vendor_name/app_name

        # Определение кэша "app"
        app: cache.adapter.redis
        default_redis_provider: redis://redis

        # Настройка других пулов кэша с уникальными именами
        pools:
            my_app_cache_pool:
                adapter: cache.adapter.redis
                provider: redis://redis
            my_system_cache_pool:
                adapter: cache.adapter.redis
                provider: redis://redis