framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                options:
                    auto_setup: true
                    persistent: true
            failed:
                dsn: 'doctrine://default?queue_name=failed_messages'
                options:
                    auto_setup: true

        routing:
            'App\Message\PostMessage': async